export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const UPDATE_PROFILE = "UPADATE_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
export const GET_REPOS = "GET_REPOS";

//
export const REGISTER_STUDENT_SUCCESS = "REGISTER_STUDENT_SUCCESS";
export const REGISTER_STUDENT_FAIL = "REGISTER_STUDENT_FAIL";
export const STUDENT_LOADED = "STUDENT_LOADED";
export const STUDENT_AUTH_ERROR = "STUDENT_AUTH_ERROR";
export const LOGIN_STUDENT_SUCCESS = "LOGIN_STUDENT_SUCCESS";
export const LOGIN_STUDENT_FAIL = "LOGIN_STUDENT_FAIL";

//
export const ADD_COURSE = "ADD_COURSE";
export const GET_COURSES = "GET_COURSES";
export const COURSES_ERROR = "COURSES_ERROR";
export const GET_FILTERED_COURSE = "GET_FILTERED_COURSE";
export const GET_COURSE_BY_AUTHOR = "GET_COURSE_BY_AUTHOR";
export const GET_COURSE_BY_ID = "GET_COURSE_BY_ID";
export const DELETE_COURSE = "DELETE_COURSE";
export const DELETE_ERROR = "DELETE_ERROR";
export const UPDATE_COURSE = "UPDATE_COURSE";
export const UPDATE_ERROR = "UPDATE_ERROR";
//
export const ADD_QUIZZ = "ADD_QUIZZ";
export const GET_QUIZZES = "GET_QUIZZES";
export const QUIZZES_ERROR = "QUIZZES_ERROR";
export const ADD_QUESTION = "ADD_QUESTION";
export const QUESTION_ERROR = "QUESTION_ERROR";
export const GET_CURRENT_QUIZZ = "GET_CURRENT_QUIZZ";
export const GET_QUIZZ_BY_COURSE_NAME = "GET_QUIZZ_BY_COURSE_NAME";
export const GET_QUIZZ_BY_AUTHOR = "GET_QUIZZ_BY_AUTHOR";
export const DELETE_QUIZZ = "DELETE_QUIZZ";

//
export const GET_CURRENT_COURSE = "GET_CURRENT_COURSE";

//
export const GET_POSTS = "GET_POSTS";
export const POST_ERROR = "POST_ERROR";
export const ADD_COMMENT = "ADD_COMMENT";
export const COMMENT_ERROR = "COMMENT_ERROR";
export const REMOVE_COMMENT = "REMOVE_COMMENT";

//
export const UPDATE_LIKES = "UPDATE_LIKES";

//
export const ADD_ASSIGNMENT = "ADD_ASSIGNMENT";
export const GET_ASSIGNMENT_BY_COURSE_NAME = "GET_ASSIGNMENT_BY_COURSE_NAME";
export const GET_ASSIGNMENT_BY_ID = "GET_ASSIGNMENT_BY_ID";
export const GET_ASSIGNMENT_BY_AUTHOR = "GET_ASSIGNMENT_BY_AUTHOR";
export const DELETE_ASSIGNMENT = "DELETE_ASSIGNMENT";

//
export const ADD_MY_COURSE = "ADD_MY_COURSE";
export const GET_COURSE_BY_STUDENT_NAME = "GET_COURSE_BY_STUDENT_NAME";

//
export const ADD_MY_QUIZ_RESULT = "ADD_MY_QUIZ_RESULT";
export const GET_QUIZ_BY_STUDENT_NAME = "GET_QUIZ_BY_STUDENT_NAME";

//
export const ADD_MY_FEEDBACK = "ADD_MY_FEEDBACK";
